### ISSUE TITLE
No longer compatible with @apollo/react-hooks v4 without passing client

### ISSUE THREAD

**Issue by webjay** [praisegeek/gatsby-plugin-appsync#6]
gatsby-plugin-appsync: 1.0.9
@apollo/react-hooks: 4.0.0 or @apollo/client: 3.1.3

> Uncaught Invariant Violation: Could not find "client" in the context or passed in as an option. Wrap the root component in an ApolloProvider, or pass an ApolloClient instance in via options.

I believe it is caused by the breaking changes mentioned here:
https://github.com/apollographql/react-apollo/blob/master/Changelog.md#400-2020-07-20

I now need to pass `client` from `import { client } from 'gatsby-plugin-appsync';` to `useQuery`.

**Comment by praisegeek** [comment]
@webjay I've been kind of away, but I'm looking through it.

**Comment by praisegeek** [comment]
@webjay the issue you encountered was as a result of using Apollo Client v3+ with gatsby-plugin-appsync's default v2.6. So that breaks when using apollo hooks such as ***useQuery***.

When using gatsby-plugin-appsync, you don't need to add `@apollo/react-hooks: 4.0.0 or @apollo/client: 3.1.3` to your dependencies because they're dependencies used by the plugin. 

NPM drop in replacement is being used to determine the right Apollo Client version for AWS AppSync by checking `GATSBY_APOLLO_CLIENT_VERSION` in your environment variables.

To use ***useQuery***, ensure WITH_HOOKS is passed to GATSBY_APOLLO_CLIENT_VERSION as an environment variable. 

```
import { useQuery } from 'react-apollo'

```

By default, when not using WITH_HOOKS, a replacement would be 

```
import { Query } from 'react-apollo-legacy'

```

'react-apollo-legacy' contains all imports for Apollo Client 2.6
'react-apollo' contains all imports for Apollo Client V3+, including Apollo React hooks.

I'll be closing this issue.
